use_frameworks!

platform :ios, '10.0'

target 'LSGAVPlayerManager_Example' do
  pod 'LSGAVPlayerManager', :path => '../'

  target 'LSGAVPlayerManager_Tests' do
    inherit! :search_paths

    
  end
end
